import {MovieDetail, SideNavigationItem} from './interfaces';

export const sideNavigationList: SideNavigationItem[] = [
  {id: 1, url: '/', name: 'Menu 1'},
  {id: 2, url: '/', name: 'Menu 2'},
  {id: 3, url: '/', name: 'Menu 3'},
  {id: 4, url: '/', name: 'Menu 4'},
  {id: 5, url: '/', name: 'Menu 5'},
  {id: 6, url: '/', name: 'Menu 6'},
  {id: 7, url: '/', name: 'Menu 7'},
];

export const movieItem: MovieDetail[] = [
  {
    id: 1,
    title: 'Title 1',
    year: '2005',
    imgUrl: 'https://www.spacex.com/static/images/backgrounds/iss_game.webp',
    rated: 'rated',
    released: 'released',
    runtime: 'runtime',
    genre: 'genre',
    director: 'director',
    writer: 'writer',
    actors: 'actors',
    plot: 'plot',
    language: 'language',
    country: 'country',
  },
  {
    id: 2,
    title: 'Title 2',
    year: '2005',
    imgUrl: 'https://www.spacex.com/static/images/backgrounds/iss_game.webp',
    rated: 'rated',
    released: 'released',
    runtime: 'runtime',
    genre: 'genre',
    director: 'director',
    writer: 'writer',
    actors: 'actors',
    plot: 'plot',
    language: 'language',
    country: 'country',
  },
  {
    id: 3,
    title: 'Title 3',
    year: '2005',
    imgUrl: 'https://www.spacex.com/static/images/backgrounds/iss_game.webp',
    rated: 'rated',
    released: 'released',
    director: 'director',
    writer: 'writer',
    actors: 'actors',
    plot: 'plot',
    language: 'language',
    country: 'country',
  },
  {
    id: 4,
    title: 'Title 4',
    year: '2005',
    imgUrl: 'https://www.spacex.com/static/images/backgrounds/iss_game.webp',
    rated: 'rated',
    released: 'released',
    runtime: 'runtime',
    genre: 'genre',
    language: 'language',
    country: 'country',
  },
];

